__author__ = 'Peter'
s = "TGATGAGTTACAATGCAACTTGAATAGACCCTGTACAGACGCCCGGGATTTTGTAGGAAAGCTCAACGTGCTAAACTTGCGGCGTCGACCCACAGTCAATACTTCTATCAAGTGGGCTAATCAGCGATGCATTTAGTTATGTCAGGAGACTTACGCTATATAAACCACATTCTCCTTCGGAGGCGTCCGGTATTGCGTAAGATGTACCGCGTTAGACGAAAGAGACTCATCTTGAGAGTAGGCCCGCACCCAGGATCCCTATATCATAGCGACGTGGAATCGCTCATTTGAATCCATAGCACGTTAGTGGGGGGGAGGACTTAGCACCGTAGGTGAGGCTGGGGCTATCCATTAGTAAGAAGGTCCCCATTAATACGACAGAATCTGTTAAGCAGGATTGATAACAATTATGGTAGAAAGCTTGCAGAGAGACGCCTACCGTCTAAATAATTGTCAACTCACTGCCACACAGATCAACGAAGTCGTAAAATCACCGTCAATCCATAGATTCAGCTGGCGTGGTCAATCAACTAGGGTACGTTTTTGTGGCCTCTACTCCAGTCAGAGCCAAGAAATTTAACATTAAAGTTGGCTAATATGCCCAGACCGCGTAAGTTATACTAGTATCGTTTCGCTACCGTCCCATTTCAGGAACGCGCCCGACTAGATTGACTCCAGTTGTTCAGGACGACAGTAAGTTACTCGGCTAAGGGCGGTGCCCGAGCCCCAGGACGGCGCCTATTGTACTCTATCAACTAATATCCCAGCGATTGAAGTAGGTCTTGCTGGCCATGTCGGGTTGCTTTCTGTTAGAAGCGTACGTGATGCACACTCCTCCCGCGGGTACATACGCCCTCGGATACATTTGGAGGCAAACATATGGCGTCATGGGTATTGCCTAGCAGATTCGTAACGGGAGACTAGAATAG"
n = 0
A = 0
T = 0
G = 0
C = 0

while n < len(s):
    if s[n] == "A":
        A += 1
        n += 1

    elif s[n] == "T":
        T += 1
        n += 1

    elif s[n] == "G":
        G += 1
        n += 1

    elif s[n] == "C":
        C += 1
        n += 1

print "A:", A
print "T:", T
print "G:", G
print "C:", C
