#!/usr/bin/perl
# Read a fasta file and extract the sequence data
use strict;
use warnings;
use biolib;
# Declare and initialize variables
my @file_data = ( );
my $dna = '';

# Read in the contents of the file "sample.dna"
@file_data = get_file_data("fasta.dns");

# Extract the sequence data from the contents of the file


$dna = get_sequence(@file_data);
# Print the sequence in lines 25 characters long
print_sequence($dna, 25);
exit;